class_path: starvlm.model.openai.OpenAIModel
init_kwargs:
  base_url: https://openrouter.ai/api/v1
  model_path: google/gemini-2.0-flash-001
  generate_kwargs:
    max_tokens: 8192
    temperature: 0.0
coordinates_adapter: null
