class_path: starvlm.model.gemma_3.GemmaModel
init_kwargs:
  model_path: google/gemma-3-27b-it
  dtype: bfloat16
  attn_implementation: flash_attention_2
  ignore_index: -100
  max_length: 8192
  requires_grad_kwargs:
    language_model_requires_grad: true
    vision_model_requires_grad: true
    connector_requires_grad: true
  generate_kwargs:
    max_new_tokens: 8192
    do_sample: false
coordinates_adapter:
  class_path: starvlm.model.coordinates_adapter.gemma_3.GemmaCoordinatesAdapter
  init_kwargs:
    model_path: google/gemma-3-27b-it
