class_path: starvlm.model.openai.OpenAIModel
init_kwargs:
  base_url: http://localhost:8000/v1
  model_path: meta-llama/Llama-3.2-11B-Vision-Instruct
  generate_kwargs:
    max_tokens: 8192
    temperature: 0.0
coordinates_adapter:
  class_path: starvlm.model.coordinates_adapter.llama_32.LlamaCoordinatesAdapter
  init_kwargs:
    model_path: meta-llama/Llama-3.2-11B-Vision-Instruct
